travis:
  secure:
    BINSTAR_TOKEN: Gk17V2CxJjVKoX6F0a2S7IHzax8KivPFy4Nup4HXYa16WGDyEKaZ2S1MOmtzk50oC82IBYLQASnwxmu2HxUFCYmxhr6DERnySzscHAWaev0t9904lxFZZPyqitPdeVZe2nRgR54ezHbXVA85fzSOVbTBAdIMoe9zz7HHZPtQ5wx1urEk2WMbvbxfNUi+kJH8FAPcrniQOJhNHuFNZaFzoYFE9Zrs/QcsTjF9hDQ/dkILCkhu6IGTFySXYo2F0dFeXk/hOYEmiIIxgNTz4isZjPrS2ZDk6y6MAEz1ajHqZcRjzdykGGCudNvf+pjgdYtSddvh/ry+meaUc2LLdGeRup3yeFIwfYpEjDMHg9EZkcrDJNDX8w4k6ANCIeBRafT9ek4SGvvOB8EhJ/iBzGUlD/F8T0y2s3+E4euj7X/3/UQ4W7QAlCxsshN61nFmk/a4y6naqk2tHoxDOGt4farF/fk7UzDknTL2F3XphtPl9ltgtOxUVXt+iGbGQG5u+x60yz/STilHGYzvjakS14uJaUYHT8hqfIHTrcy5S/i+QF4JkFkcMuxCLE238kFyB+ObW6G5mKlKUYB5My4Gslu3VMdby/qXc9VNSTwzqOsnFLAOfa6oRNC3GCMN1ZlBWt8MUqdS+uCG1x/T/srsDjRXh2z1BSG2G7wMTMt2BuhykE8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
