travis:
  secure:
    BINSTAR_TOKEN: MVdJX9fWPGkvCiwdnYXXO5TKyPqOh9wx51cbH7xtL2B2Oh4WmoDo5RQI9Q01joo70AtJMbKAVizHu/3k/9YZBphwxLMCjWRdefhyeZo/1nI/T4oeS2aQ16LmHUqzgGDUMs9+9rasQI4UjsWZKRgl7R1VH82Dfk9af3YWDleAHOal4b0QYdc9at0pnhPphnAWp/M4+A70Hxo4LitI61PlqD4txRZw/wDj824Vpqxrr5rl813Nj4n+KkIHbp8lWN2BCRLJ08IwLYeU7yYIVHYyDwYwB6jeFb882P9bD5TDeLpr0Pz0To7Yt3Gi8bKAp4o90xV6Y/oga6E9pr2ykaiuaDYvLomc+xHLHsxObqO8LaU2C+A2VZkyw5BnveoLr5ad5su0ARfQBszcwQfth71biRIhHBvO6U1RruN+AizKFEMDmQ8TzsDuximJ8O7jL7yntcee02jcGeZwHKjAzfVlNpSPKLpFwmgFsA2DfChetOZtNEAaTaugAqiNSeS+J8rit4YDctvJwWjsuQRPIqkBZLRiKHrbKYLZCD6nFwlbPAZfoE29q2SAHNVfKy44H33/6vy35ADj6nLC0Umpi+AhPf/8ZnQsqHaLNWbKEiTTDzKO9NVzldr2j5pXdgDqIsjk2QEaUuiDXsR7z8W213bcl8g/jsT8dZ67lg02OHgYHaU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
