travis:
  secure:
    BINSTAR_TOKEN: e5Zkfw/lNcql2RqbfZpHwz5cUNwAdRT/57Pv7oz1bCWBDJHFfumcD53+FDAwPaZa8g2i4x4BsNMgZwn1aTZ8hGJLRNpQBEZbac3QLpURhVIt3nkyj3xXN5L1eK5iZUlsgxWT3G6egEz2/NZJprZenYcA0OD76wm8ym01fAJODboAdXsUk5Yx073Ds4UIXaC4vKtO3d5OLQTvAOuwKQFUyP0EnMK7VJrrxc9U8bn4okiJ1RqJYzb7efjcQBuy02zCZncYmhoaa9Lieruc6tt6pFm7rFu1CvmECuKm6f0YJ0tYB5q1yQs5FVaWpVt8zR1WO1zwAKDJv8mBhGg31clOHHWQp+vjnV6VXHdeV/4KCH1qskCuCmUSC6086fJMFC8jmLJPsmx1vbTTfeFG/Q/LeD0rNj/5jQC5W97nZB2+qEAOA3a36b9eCla4UYUc8iKQk6nfhzlWqJWrXC1UYoD/Rn1q+Jofa81I+oK7WP0l6/wDplNZt4Cvlf9Tg2aku+9OwgiD729db1eXQxMTtIuMM01lNLEwMxNiqRv7h6Tb/Pq1Tp/PtrisLvxm8PcxRL3cemwBTwFdW7khtfwhYqAXdcZK+EmILIydepBMh5cMndFEpssdLMb8DxHIPqTZIS59JtHyED8riqfspklAHpc88rOQ5/sNkaWc99gmrFziuVU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
